export const products = [
  {
    id: 1,
    categoryId: 1,
    productName: "Example1",
    quantityPerUnit: "10 Box",
    favorite: false,
    unitsInStock: 12,
    unitPrice: 100,
    date: "30.12.2021",
  },
  {
    id: 2,
    categoryId: 4,
    productName: "Example2",
    quantityPerUnit: "10 Box",
    favorite: false,
    unitsInStock: 12,
    unitPrice: 100,
    date: "30.12.2021",
  },
  {
    id: 3,
    categoryId: 3,
    productName: "Example3",
    quantityPerUnit: "10 Box",
    favorite: false,
    unitsInStock: 12,
    unitPrice: 100,
    date: "30.12.2021",
  },
  {
    id: 4,
    categoryId: 2,
    productName: "Example4",
    quantityPerUnit: "10 Box",
    favorite: false,
    unitsInStock: 12,
    unitPrice: 100,
    date: "30.12.2021",
  },
  {
    id: 5,
    categoryId: 2,
    productName: "Example5",
    quantityPerUnit: "10 Box",
    favorite: true,
    unitsInStock: 12,
    unitPrice: 100,
    date: "30.12.2021",
  },
  {
    id: 6,
    categoryId: 3,
    productName: "Example6",
    quantityPerUnit: "10 Box",
    favorite: true,
    unitsInStock: 12,
    unitPrice: 100,
    date: "30.12.2021",
  },
  {
    id: 7,
    categoryId: 2,
    productName: "Example7",
    quantityPerUnit: "10 Box",
    favorite: true,
    unitsInStock: 12,
    unitPrice: 100,
    date: "30.12.2021",
  },
  {
    id: 8,
    categoryId: 1,
    productName: "Example8",
    quantityPerUnit: "10 Box",
    favorite: false,
    unitsInStock: 12,
    unitPrice: 100,
    date: "30.12.2021",
  },
];
